# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-11 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.CharField(max_length=8000),
        ),
    ]
